include $(call all-makefiles-under,$(LOCAL_PATH))
# include $(CLEAR_VARS)
# LOCAL_MODULE := busybox
# LOCAL_MODULE_TAGS := optional
# LOCAL_MODULE_CLASS := EXECUTABLES
# LOCAL_MODULE_STEM := $(LOCAL_MODULE)
# LOCAL_SRC_FILES := $(TARGET_ARCH)/$(LOCAL_MODULE)
# include $(BUILD_PREBUILT)
